[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\n/home/bcva)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x84\0\0\x2\xf8\0\0\t\xfa\0\0\x5\x97\0\0\a\x84\0\0\x2\xf8\0\0\t\xfa\0\0\x5\x97\0\0\0\0\0\0\0\0\x14\0\0\0\a\x84\0\0\x2\xf8\0\0\t\xfa\0\0\x5\x97)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
QtStyle=Fusion
adv-controls=0
bgSize=@Size(1268 598)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x82\0\0\0\xd8\0\0\f~\0\0\x4s\0\0\a\x82\0\0\0\xd8\0\0\f~\0\0\x4s\0\0\0\0\0\0\0\0\x14\0\0\0\a\x82\0\0\0\xd8\0\0\f~\0\0\x4s)

[RecentsMRL]
list=file:///run/media/bcva/Danzo/Video%20Assist_0017.mov, file:///run/media/bcva/Danzo/Video%20Assist_0032.mov, file:///run/media/bcva/Danzo/Bike%20Test%20Cine%20Sun.mp4, file:///run/media/bcva/Danzo/._DJI%20Mini%205%20Pro%20Test%20Footage%201%20-%20Arc.mov, file:///run/media/bcva/Danzo/Video%20Assist_0033.mov, file:///run/media/bcva/Danzo/EDIT%20V1.mp4, file:///run/media/bcva/Gojo/Anime_TV_Shows_Series_Movies/Bleach/Bleach_Episode_059.mkv, file:///run/media/bcva/Gojo/Anime_TV_Shows_Series_Movies/Bleach/Bleach_Episode_052.mkv
times=66099, 0, 95150, 0, 0, 0, 222957, 0
