# Prefer Japanese audio
alang=jpn,japanese,ja

# Prefer English subtitles
slang=eng,en

# Auto-load subtitles if available
sub-auto=fuzzy

# Optional: Always enable subtitles
sub=auto

# Get Rid Of Title Bar
border=no