background_opacity 0.5
hide_window_decorations yes
cursor_hide yes
confirm_os_window_close 0

map ctrl+equal    increase_font_size
map ctrl+minus    decrease_font_size
map ctrl+shift+backspace reset_font_size
